# Generated by Django 3.0.2 on 2020-02-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerRank',
            field=models.IntegerField(default=0),
        ),
    ]
