# Generated by Django 3.0.5 on 2020-04-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0002_threat_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='adviceKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.Advice'),
        ),
    ]
