# Generated by Django 2.2.6 on 2020-02-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0002_answer_answerrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='threatKey',
        ),
        migrations.AddField(
            model_name='threat',
            name='adviceKey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.Advice'),
            preserve_default=False,
        ),
    ]
