# Generated by Django 3.0.4 on 2020-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0002_advice_threatid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='threatID',
        ),
        migrations.AddField(
            model_name='question',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
