# Generated by Django 3.0.4 on 2020-04-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0003_auto_20200405_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='threatKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.Threat'),
        ),
    ]
