# Generated by Django 2.2.6 on 2020-02-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0003_auto_20200217_2354'),
        ('KnowledgeBase', '0003_auto_20200217_1848'),
    ]

    operations = [
    ]
