# Generated by Django 3.0.4 on 2020-04-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0005_question_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='questionKey',
        ),
    ]
