# Generated by Django 3.0.4 on 2020-04-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0006_auto_20200405_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questionKey',
            new_name='question',
        ),
    ]
