# Generated by Django 3.0.4 on 2020-04-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0008_auto_20200405_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answerRank',
            new_name='questionRank',
        ),
    ]
