# Generated by Django 3.0.4 on 2020-04-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0010_vulnerability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('vulnerabilityKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.Vulnerability')),
            ],
        ),
    ]
