# Generated by Django 3.0.4 on 2020-04-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0011_severitylevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severitylevel',
            name='level',
            field=models.CharField(max_length=200),
        ),
    ]
