# Generated by Django 3.0.4 on 2020-04-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0012_auto_20200405_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countermeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employedDate', models.DateField(auto_now_add=True)),
                ('CountermeasureText', models.CharField(max_length=200)),
                ('vulnerabilityKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.Vulnerability')),
            ],
        ),
    ]
