# Generated by Django 3.0.4 on 2020-04-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0015_ciaacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='vulnerabilityKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.Vulnerability'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='attackerKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.Attacker'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='ciaaKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.CiaaCategory'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='countermeasureKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.Countermeasure'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='severityLevelKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.SeverityLevel'),
        ),
    ]
