# Generated by Django 3.0.5 on 2020-04-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0003_auto_20200416_1652'),
        ('KnowledgeBase', '0016_auto_20200405_1726'),
    ]

    operations = [
    ]
