# Generated by Django 2.2.6 on 2020-04-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0017_merge_20200417_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacker',
            name='vulnerabilityKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KnowledgeBase.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='vulnerabilityKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='attackerKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KnowledgeBase.Attacker'),
        ),
    ]
